### ISSUE TITLE
Filename Validation can't handle path with directories

### ISSUE THREAD

**Issue by MarkusPorti** [FahrJo/datanorm-python#1]
**Problem**
When creating a `DatanormBaseFile` with a path containing some directories in which the DATANORM.001 file is stored, the method `file_name_is_valid()` returns `False`, but should return `True`.

Code to reproduce:
```python
import datanorm as dn

base = dn.DatanormBaseFile('./data/Datanorm/DATANORM.001')
base.file_name_is_valid()
```

**Comment by FahrJo** [comment]
You are right. Should be solved with [095877e](https://github.com/FahrJo/datanorm-python/commit/095877ec28a4c0e5f3641916fec2716addcfb5d0) / [Release 0.0.2-alpha](https://pypi.org/project/datanorm/). Thank you for reporting 👍
